# Generated by Django 6.0.3 on 2026-03-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=50)),
                ('transaction_details', models.CharField(blank=True, max_length=255)),
                ('carrier', models.CharField(choices=[('DHL', 'DHL'), ('DHL_CASH', 'DHL Cash'), ('FEDEX', 'FedEx'), ('UPS', 'UPS'), ('OTHER', 'Other')], default='DHL', max_length=50)),
                ('date_of_payment', models.DateTimeField(blank=True, null=True)),
                ('date_of_payment_to_carrier', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'UnPaid')], default='UNPAID', max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('payment_made', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_of_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
