# Generated by Django 6.0.3 on 2026-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date_of_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date_of_payment_to_carrier',
            field=models.DateField(blank=True, null=True),
        ),
    ]
