# Generated by Django 6.0.3 on 2026-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipmentvat'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentvat',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
